config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :users
  root "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks, dependent: :destroy
    has_one_attached :profile_picture

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task, :type_of_task, :description, :user_id, :completed)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    puts "hey #{params[:id]}"
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :tasks, :profile_picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">

    <div class="field">
      <%= form.label :task %>
      <%= form.text_field :task %>
    </div>

    <div class="field">
      <%= form.label :type_of_task %>
      <%= form.text_field :type_of_task %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :completed %>
      <%= form.check_box :completed %>
    </div>

    <div class="field">
      <%= form.label :user_id %>
      <%= form.collection_select(:user_id, User.all, :id, :username) %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

  <div class="taskShow">
    <%= link_to 'New Task', new_task_path %>
    <% @tasks.each do |task| %>
      <div class="single">
        <h4>Task: </h4>
        <%= task.task %> </br>
        <h4>Type: </h4>
        <%= task.type_of_task %>  </br>
        <h4>Status: </h4>
        <%= task.completed ? "Completed" : "Not Completed" %>
        <h4>Description: </h4>
        <%= task.description %> 
        <nav>
          <%= link_to 'Show', task %>
          <%= link_to 'Edit', edit_task_path(task) %>
          <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
        </nav>
      </div>
    <% end %>
  </div>

<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="taskShow">
      <div class="single">
        <h4>Task: </h4>
        <%= @task.task %> </br>
        <h4>Type: </h4>
        <%= @task.type_of_task %>  </br>
        <h4>Status: </h4>
        <%= @task.completed ? "Completed" : "Not Completed" %>
        <h4>Description: </h4>
        <%= @task.description %>
        <h4>User:</h4> 
        <%= @task.user ? @task.user.username :  "User not found" %>
        <nav>
          <%= link_to 'Edit', edit_task_path(@task) %>
        </nav>
      </div>
  </div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">

    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field profile-pic">
      <%= form.label :profile_picture %>
      <%= form.file_field :profile_picture %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.text_field :password %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<div class="new_user"><%=  link_to 'New User', new_user_path %></div>
  <div class="users">
  <%# <%= image_tag 'image.png', width: '100px' %> 
    <% @users.each do |user| %>
    <div class='user-container'>
      <div class="user">
        <div class="profile">
          <div>
            <%= image_tag user.profile_picture.attached? ? user.profile_picture : 'image.png', class: 'image' %>
          </div>
          <div>
            <h4>Username</h4>
            <p><%= user.username %></p>
          </div>
        </div>
        <div>
          <h4>Email</h4>
          <p><%= user.email %></p>
        </div>
        <div class="tasks"><% user.tasks.each do |task| %>
          <strong>Task: </strong>
            <p> <%= task.task %> </p>
            <strong>Type: </strong>
            <p> <%= task.type_of_task %> </p> 
            <strong>Status: </strong>
            <p> <%= task.completed ? "Completed" : "Not Completed" %></p>
            <strong>Description: </strong>
            <p> <%= task.description %> </p> 
          <% end %></div>
        </div>
        <div class="links">
          <%= link_to 'More', user %>
          <%= link_to 'Edit', edit_user_path(user) %>
          <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %>
  </div>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="userShow">
  <div class="single profileTag">
    <div>
      <%= image_tag @user.profile_picture.attached? ? @user.profile_picture : 'image.png', class: "image"%>
    </div>
    <div>
      <strong><%= @user.username %></strong>
    </div>
    <div>
      <%= @user.email %>
    </div>
    <div class="profileTagLinks">
      <%= link_to 'Edit', edit_user_path(@user) %> 
      <%= link_to 'Back', users_path %> 
      <a href="/tasks/new">New Task</a>
    </div>
  </div>
  

  <div>
    <% @user.tasks.each do |task| %>
      <div class="single">
        <h4>Task: </h4>
        <%= task.task %> </br>
        <h4>Type: </h4>
        <%= task.type_of_task %>  </br>
        <h4>Status: </h4>
        <%= task.completed ? "Completed" : "Not Completed" %>
        <h4>Description: </h4>
        <%= task.description %>  
        <nav>
          <%= link_to 'Edit', href="/tasks/#{task.id}/edit" %>
          <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %>
        </nav>
      </div>
    <% end %>
    
  </div>
</div>